import AppLoading from 'expo-app-loading';
import {
    useFonts as expoUseFonts,
    SourceSerifPro_200ExtraLight,
    SourceSerifPro_200ExtraLight_Italic,
    SourceSerifPro_300Light,
    SourceSerifPro_300Light_Italic,
    SourceSerifPro_400Regular,
    SourceSerifPro_400Regular_Italic,
    SourceSerifPro_600SemiBold,
    SourceSerifPro_600SemiBold_Italic,
    SourceSerifPro_700Bold,
    SourceSerifPro_700Bold_Italic,
    SourceSerifPro_900Black,
    SourceSerifPro_900Black_Italic,
} from '@expo-google-fonts/source-serif-pro';
import {
    useFonts as expoUseFonts,
    SourceCodePro_200ExtraLight,
    SourceCodePro_300Light,
    SourceCodePro_400Regular,
    SourceCodePro_500Medium,
    SourceCodePro_600SemiBold,
    SourceCodePro_700Bold,
    SourceCodePro_800ExtraBold,
    SourceCodePro_900Black,
    SourceCodePro_200ExtraLight_Italic,
    SourceCodePro_300Light_Italic,
    SourceCodePro_400Regular_Italic,
    SourceCodePro_500Medium_Italic,
    SourceCodePro_600SemiBold_Italic,
    SourceCodePro_700Bold_Italic,
    SourceCodePro_800ExtraBold_Italic,
    SourceCodePro_900Black_Italic,
} from '@expo-google-fonts/source-code-pro';

export const useFonts = () => {
    return expoUseFonts({
        SourceSerifPro_200ExtraLight,
        SourceSerifPro_200ExtraLight_Italic,
        SourceSerifPro_300Light,
        SourceSerifPro_300Light_Italic,
        SourceSerifPro_400Regular,
        SourceSerifPro_400Regular_Italic,
        SourceSerifPro_600SemiBold,
        SourceSerifPro_600SemiBold_Italic,
        SourceSerifPro_700Bold,
        SourceSerifPro_700Bold_Italic,
        SourceSerifPro_900Black,
        SourceSerifPro_900Black_Italic,
        SourceCodePro_200ExtraLight,
        SourceCodePro_300Light,
        SourceCodePro_400Regular,
        SourceCodePro_500Medium,
        SourceCodePro_600SemiBold,
        SourceCodePro_700Bold,
        SourceCodePro_800ExtraBold,
        SourceCodePro_900Black,
        SourceCodePro_200ExtraLight_Italic,
        SourceCodePro_300Light_Italic,
        SourceCodePro_400Regular_Italic,
        SourceCodePro_500Medium_Italic,
        SourceCodePro_600SemiBold_Italic,
        SourceCodePro_700Bold_Italic,
        SourceCodePro_800ExtraBold_Italic,
        SourceCodePro_900Black_Italic,
    });
};

export const colors = {
    // Colors
    primary_white: '#ECE9E6',
    light_blue: '#ABB3C5',
    dark_blue: '#494F64',
    white: '#FFFFFF',
    pinky: '#E0A6AA',
    yellow_mellow: '#EDD3B2',
};

export const fonts = {
    ss_extra_light: 'SourceSerifPro_200ExtraLight',
    ss_extra_light_italic: 'SourceSerifPro_200ExtraLight_Italic',
    ss_light: 'SourceSerifPro_300Light',
    ss_light_italic: 'SourceSerifPro_300Light_Italic',
    ss_regular: 'SourceSerifPro_400Regular',
    ss_regular_italic: 'SourceSerifPro_400Regular_Italic',
    ss_semibold: 'SourceSerifPro_600SemiBold',
    ss_semibold_italic: 'SourceSerifPro_600SemiBold_Italic',
    ss_bold: 'SourceSerifPro_700Bold',
    ss_bold_italic: 'SourceSerifPro_700Bold_Italic',
    ss_black: 'SourceSerifPro_900Black',
    ss_black_italic: 'SourceSerifPro_900Black_Italic',

    sc_extra_light: 'SourceCodePro_200ExtraLight',
    sc_light: 'SourceCodePro_300Light',
    sc_regular: 'SourceCodePro_400Regular',
    sc_medium: 'SourceCodePro_500Medium',
    sc_semibold: 'SourceCodePro_600SemiBold',
    sc_bold: 'SourceCodePro_700Bold',
    sc_extra_bold: 'SourceCodePro_800ExtraBold',
    sc_black: 'SourceCodePro_900Black',
    sc_extra_light_italic: 'SourceCodePro_200ExtraLight_Italic',
    sc_light_italic: 'SourceCodePro_300Light_Italic',
    sc_regular_italic: 'SourceCodePro_400Regular_Italic',
    sc_medium_italic: 'SourceCodePro_500Medium_Italic',
    sc_semibold_italic: 'SourceCodePro_600SemiBold_Italic',
    sc_bold_italic: 'SourceCodePro_700Bold_Italic',
    sc_extra_bold_italic: 'SourceCodePro_800ExtraBold_Italic',
    sc_black_italic: 'SourceCodePro_900Black_Italic',

};

export default {
    useFonts,
    colors,
    fonts,
}
